### ISSUE TITLE
Extract media query from the entire bundle

### ISSUE THREAD

**Issue by Loykos** [SassNinja/media-query-plugin#1]
Hi,

I'd like your plugin! It would be amazing if I could extract from the entire bundles. Es:

```javascript
// webpack.config.js
module.exports = {
    context: path.resolve(__dirname, 'WebSrc'),
    entry: {
        page: './js/page.js',
    },
    [...]
    module: {
        rules: [
            {
                test: /\.s?css$/,
                use: [
                    MiniCssExtractPlugin.loader,
                    {
                        loader: 'css-loader',
                        options: {
                            importLoaders: 2,
                            sourceMap: true
                        }
                    },
                    MediaQueryPlugin.loader,
                    {
                        loader: 'postcss-loader',
                        options: {
                            plugins: () => [
                                require('autoprefixer')(),
                            ],
                            sourceMap: true
                        }
                    },
                    {
                        loader: 'sass-loader',
                        options: {
                            sourceMap: true
                        }
                    }
                ]
            },
            [...]
        ]
    },
    optimization: {
        splitChunks: {
            minSize: 1,
            cacheGroups: {
                js: {
                    test: /\.js$/,
                    name: "commons",
                    chunks: "all",
                    minChunks: 7,
                },
                css: {
                    test: /\.s?css$/,
                    name: "commons",
                    chunks: "all",
                    minChunks: 7,
                },
            }
        }
    },
    plugins: [
        new MiniCssExtractPlugin({
            // Options similar to the same options in webpackOptions.output
            // both options are optional
            filename: "dist/[name].css",
        }),
        new MediaQueryPlugin({
            include: true,
            queries: {
                '(min-width: 1200px)': 'xl'
            }
        }),
    ],
};
```

```javascript
// page.js
import "./a.scss";
import "./b.scss";
```

This configuration will generate `page.js` and `page.css` dist files. I'd like to extract media query from entry and not from components (`a.scss`, `b.scss`). I'd like something like `page.css`, `page-xl.css` and so on.

Thank you for your help.

**Comment by SassNinja** [comment]
Hi @Loykos,
thanks for your feature request!

So if I understood you correctly you need an option to adjust the target name for the injection. Something to change `[chunk name]-[query]` into `[entry name]-[query]`.

I'm not sure how easy it is to get the entry point of a chunk. I can take a look at the weekend.

But wouldn't it be an option for you to just create `page.scss` for this?
```javascript
// page.js
import './page.scss';
```
```scss
// page.scss
import './a.scss';
import './b.scss';
```

**Comment by Loykos** [comment]
Thanks for you for answer. The problem is that if I import `page.scss` inside `page.js` I lost the `splitChunks` features for css. Because webpack consider the result of `page.scss` as a unique module import and doesn't manage @import inside css files.

**Comment by SassNinja** [comment]
After some research I think it's not possible because I would have to know the entry's name within the loader context what is not possible.

The only thing I can offer is a group feature which lets you map certain chunks to a name.
The following will then generate your desired `page-[query]`
```javascript
new MediaQueryPlugin({
    groups: {
        page: ['a', 'b']
    }
})
```

What do you think @Loykos? Would this be an option for you?

**Comment by Loykos** [comment]
I think it can be a good option. Does it catch also the result from splitChunks option?

**Comment by SassNinja** [comment]
Depends on what you expect. In my tests everything gets extracted into the desired file.

So if you're using splitChunks with a cacheGroup `commons` you'll get a `commons.css` (with common CSS) and a `page-[query].css` (with the extracted CSS incl. common)

You can test it yourself and let me know if this fixes your problem
```bash
npm install --save-dev git+https://github.com/SassNinja/media-query-plugin.git#feature/groups-option
```

**Comment by SassNinja** [comment]
@Loykos did you already manage to take a look?

As it looks good to me I'll close this feature request & merge my PR.

**Comment by Loykos** [comment]
Sorry for my late answer. The "groups" option works but I still list all css components I import for each page. At the moment I try to use this option and I hope new feature to extract media queries from the entries.

Thank you!
