### ISSUE TITLE
Using Regular Expression for group matching throws ERROR

### ISSUE THREAD

**Issue by dNitro** [SassNinja/media-query-plugin#20]
When using with the following config:
```javascript
new MediaQueryPlugin({
  include: true,
  queries: {
    'screen and (min-width: 1000px)': 'desktop'
  },
  groups: {
    app: /^example/
  }
});
```
modules that doesn't get matched with group RegExp throws TypeError:
```
(node:31262) UnhandledPromiseRejectionWarning: TypeError: group.indexOf is not a function
    at /Users/david/Projects/new/app:1:48
    at getGroupName (/Users/david/Projects/new/node_modules/media-query-plugin/src/postcss.js:29:52)
    at callback (/Users/david/Projects/new/node_modules/media-query-plugin/src/postcss.js:42:35)
    ...
```
Seems `typeof group === 'object'` guard on [line 29 of `src/postcss.js`](https://github.com/SassNinja/media-query-plugin/blob/13012c0bc18568bdc8453c6afd92c3e2370a4e28/src/postcss.js#L29) should be more stricter and check if group is array. Regexps are object and when their names does not get match on previous line, pass this guard and get to `group.indexOf` which obviously does not exist on regular expressions.

**Comment by SassNinja** [comment]
Good catch!

Seems I totally lost track of this.
It's going to be fixed in release 1.3.2
