### ISSUE TITLE
Extracted files are not available in html-webpack-plugin

### ISSUE THREAD

**Issue by in-in** [SassNinja/media-query-plugin#22]
I'm trying to access `htmlWebpackPlugin.files.extracted.css`, but I get a error
```shell
ERROR in Template execution failed: TypeError: Cannot read property 'css' of undefined
```

It started after I updated the `html-webpack-plugin` `3.2.0` -> `4.2.1`

```json
"media-query-plugin": "1.3.1",
"html-webpack-plugin": "4.2.1",
"webpack": "4.43.0",
```

**Comment by yashiel** [comment]
same issue for me. can't figure out how to solve it.
