### ISSUE TITLE
media-query-plugin vs. postcss-combine-media-query

### ISSUE THREAD

**Issue by rpb138** [SassNinja/media-query-plugin#24]
Hi,

Could you explain the difference between **media-query-plugin** and **postcss-combine-media-query**, please?

Thanks so much.

**Comment by SassNinja** [comment]
Hi @rpb138 

`media-query-plugin` is a webpack plugin which extracts media query rules from your CSS file(s) and places them in other files so you're able to load them on demand (e.g. only on desktop)

`postcss-combine-media-query` is a PostCSS plugin meaning you can use with any build tool (it's not limited to webpack) to combine equal media query rules.

So the former is about extraction (multiple files) whereas the latter is about minimization (same file).

I hope has made the differences clear.
