### ISSUE TITLE
How does this plugin work with when MiniCssExtractPlugin set "filename: '[name].[chunkhash].css'"

### ISSUE THREAD

**Issue by Garfield550** [SassNinja/media-query-plugin#9]
OS: macOS
Node.js: 10.10.0
Webpack.js: 4.17.2

In `webpack.common.js` i set "HtmlWebpackPlugin"
```js
new HtmlWebpackPlugin({
  template: 'src/index.html',
  title: '<titleName is private>',
  inject: false,
  hash: true
})
```

in `webpack.prod.js` i set "MiniCssExtractPlugin" and "MediaQueryPlugin"
```js
{
  test: /\.(css|less)$/,
  use: [
    MiniCssExtractPlugin.loader,
    'css-loader',
    MediaQueryPlugin.loader,
    'less-loader'
  ]
}
```

```js
new MiniCssExtractPlugin({
  filename: '[name].[chunkhash].css',
  chunkFilename: '[id].[chunkhash].css'
}),
new MediaQueryPlugin({
  queries: {
    'only screen and (min-width : 1224px)': 'des',
    'only screen and (min-width : 1824px)': 'des'
  }
}),
```

When I test `<%= htmlWebpackPlugin.files.css %>` in my template "index.html", the output is: 
```
1.f4287f359b9e6948080b.css?3533f6c79b197d7a89c7,main.4cfc85247524759bf20d.css?3533f6c79b197d7a89c7
```
but the `<%= htmlWebpackPlugin.files.extracted.css %>` is a blank line.

So how could I change my settings so as to bring the plugin into use?

**Comment by Garfield550** [comment]
My template `index.html` is:
```ejs
<!--
 Copyright (c) 2018 Garfield Lee
 
 This software is released under the MIT License.
 https://opensource.org/licenses/MIT
-->

<!DOCTYPE html>
<html lang="ja-JP">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><%= htmlWebpackPlugin.options.title %></title>
    <% htmlWebpackPlugin.files.css.forEach(function(cssFile) { %>
        <link rel="stylesheet" href=<%= cssFile %>>
    <% }) %>
    <% htmlWebpackPlugin.files.css.forEach(function(cssFile) { %>
        <link rel="stylesheet" href=<%= cssFile.file %> media=<%= cssFile.query %>>
    <% }) %>
</head>
<body>
    <div id="root"></div>
    <% htmlWebpackPlugin.files.js.forEach(function(jsFile) { %>
        <script src=<%= jsFile %>></script>
    <% }) %>
</body>
</html>
```

**Comment by SassNinja** [comment]
@Garfield550 thanks for reporting the issue.

But I'm unable to reproduce it. In my examples folder it works as expected. 
What I noticed is your example `index.html` has an error: you're not using `htmlWebpackPlugin.files.extracted.css` for the 2nd loop.
Maybe this solves your problem.

If not please provide a gist or example github repo to repoduce the issue.

**Comment by Garfield550** [comment]
@SassNinja I create a [repo](https://github.com/Garfield550/test-media-query-plugin) to reproduce this issue.

If run at `production` mode (`yarn run publish`), can get an ERROR: 
```console
ERROR in Template execution failed: TypeError: Cannot read property 'forEach' of undefined

ERROR in   TypeError: Cannot read property 'forEach' of undefined

  - index.html:106
    /Users/.../Projects/test-media-query-plugin/src/index.html:106:40

  - index.html:123 module.exports
    /Users/.../Projects/test-media-query-plugin/src/index.html:123:3

  - index.js:284 Promise.resolve.then
    [test-media-query-plugin]/[html-webpack-plugin]/index.js:284:18
```

**Comment by SassNinja** [comment]
@Garfield550 I've find out what's wrong with your code:
you did not specify the `include` option of the plugin!

As a result no media queries get extracted and therefore the template throws an error (`htmlWebpackPlugin.files.extracted.css` is undefined and cannot be used for iteration)

Since this is a problem with your setup and template I can't do anything. The only possibility from my side is making sure `htmlWebpackPlugin.files.extracted.css` is never `undefined` but e.g. an empty array so that the iteration won't fail.
But **I won't do this** because it'll create the impression css has been extracted and might cause issues for users that have a condition to check if css was extracted.

There are two possibilities for you to fix it:

1. specify the `include` option https://github.com/SassNinja/media-query-plugin#include
```javascript
new MediaQueryPlugin({
  include: true,
  queries: { ... }
})
```

2. consider empty object in your template

```html
<% if (htmlWebpackPlugin.files.extracted.css) { %>
    <% htmlWebpackPlugin.files.extracted.css.forEach(function(cssFile) { %>
        <link rel="stylesheet" href=<%= cssFile.file %> media=<%= cssFile.query %>>
    <% }) %>
<% } %>
```

**Comment by Garfield550** [comment]
@SassNinja thanks a lot!

**Comment by SassNinja** [comment]
@Garfield550 you're welcome!

And if you like my plugin: a github star is appreciated :wink:
